services:
    _defaults:
        public: false

    Summa\Bundle\BadgeBundle\Command\BadgeScheduleCommand:
        arguments:
            - '@doctrine'
            - '@oro_message_queue.client.message_producer'
        tags:
            - { name: console.command }