parameters:
  summa_badge.entity.badges.class: 'Summa\Bundle\BadgeBundle\Entity\Badge'

services:
  summa_badge.datagrid.event_listener.summa-badge-grid:
    class: Summa\Bundle\BadgeBundle\DataGrid\EventListener\ProductBadgeGridEventListener
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@oro_datagrid.provider.selected_fields'
    tags:
      - { name: kernel.event_listener, event: oro_datagrid.orm_datasource.result.after.summa-badge-grid, method: onResultAfter }

  summa_badge.layout.extension.product_badge_aware_context_configurator:
    class: Summa\Bundle\BadgeBundle\Layout\Extension\ProductBadgeAwareContextConfigurator
    arguments:
      - '@oro_config.manager'
    tags:
      - { name: layout.context_configurator }

  summa_badge.event_listener.badge_datagrid:
    class: Summa\Bundle\BadgeBundle\EventListener\BadgeDatagridListener
    tags:
      - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.summa-badge-grid, method: onBuildBefore }

  summa_badge.layout.data_provider.product_badges:
    class: 'Summa\Bundle\BadgeBundle\Layout\DataProvider\ProductBadgeProvider'
    arguments:
      - '@doctrine.orm.entity_manager'
    tags:
      - { name: layout.data_provider, alias: summa_product_badges_provider }

  summa_badge.badge.entity_listener.badge_entity_listener:
    class: Summa\Bundle\BadgeBundle\Entity\EntityListener\BadgeEntityListener
    public: true
    arguments:
      - '@summa_badge.builder.product_relations_builder'
    tags:
      - { name: doctrine.event_listener, event: postFlush}

  summa_badge.badge.assigment_product.processor:
    class: Summa\Bundle\BadgeBundle\Async\BadgeProductAssigmentProcessor
    arguments:
      - '@doctrine'
      - '@summa_badge.builder.product_relations_builder'
      - '@logger'
    tags:
      - { name: oro_message_queue.client.message_processor }

  summa_badge.compiler.abstract_rule_compiler:
    class: Summa\Bundle\BadgeBundle\Compiler\AbstractRuleCompiler
    abstract: true
    arguments:
      - '@oro_product.expression.parser'
      - '@oro_product.expression.preprocessor'
      - '@oro_product.expression.node_to_query_designer_converter'
      - '@oro_product.expression.query_converter'
      - '@oro_product.expression.query_expression_builder'
      - '@oro_pricing.cache.rule_cache'
      -
  summa_badge.compiler.product_assignment_rule_compiler:
    class: Summa\Bundle\BadgeBundle\Compiler\ProductAssignmentRuleCompiler
    parent: summa_badge.compiler.abstract_rule_compiler

  summa_badge.compiler.date_condition_compiler:
    class: Summa\Bundle\BadgeBundle\Compiler\DateConditionCompiler
    parent: summa_badge.compiler.abstract_rule_compiler
    calls:
      - [ setRegistry, [ '@doctrine' ] ]

  summa_badge.builder.product_relations_builder:
    class: Summa\Bundle\BadgeBundle\Builder\ProductRelationsBuilder
    arguments:
      - '@doctrine'
      - '@summa_badge.compiler.product_assignment_rule_compiler'
      - '@summa_badge.compiler.date_condition_compiler'
      - '@logger'

